# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoSpark' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoSpark

    pod 'RxAlamofire'
    pod 'ObjectMapper'
    pod 'RxSwift'
    pod 'SDWebImage', '~> 5.0'


  target 'GoSparkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoSparkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
